config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #Home Page
  root to: "users#index"
  get "/", to: "users#index", as: "home"

  #About Page
  get "/about", to: "users#about", as: "about"

  #Donate Page
  get "/donate", to: "users#donate", as: "donate"

  #User Dashboard
  get "/dashboard/:id", to: "users#dash", as: "dashboard"

  #Create new artwork item
  get "/items/new", to: "items#new", as: "new_item"
  post "/items", to: "items#create"

  #Show all art
  get "/items/all", to: "items#index", as: "all_items"

  #Show individual piece of art
  get "/items/:id", to: "items#show", as: "item"

  # Remove item listing
  delete "/items/:id", to: "items#destroy"

  #New Artist
  get "/artists/new", to: "artists#new", as: "new_artist"
  post "/artists", to: "artists#create"

  #Artist Profile
  get "/artists/:id/edit", to:"artists#edit", as: "edit_artist"
  put "/artists/:id", to: "artists#update"
  patch "/artists/:id", to: "artists#update"

  #Show Artists
  get "/artists/all", to: "artists#index", as: "all_artists"

  # Show individual Artist
  get "/artists/:id", to: "artists#show", as: "artist"
  
  # Sales/Purchase History 
  get "/orders/purchases", to: "orders#purchases", as: "purchases"
  get "/artists/:id/sales", to: "artists#sales", as: "sales"

  #New Order
  get "/orders/new", to: "orders#new", as: "new_order"

  #Order complete
  get "/orders/complete", to: "orders#complete"

  #Order Webhook
  post "/orders/webhook", to: "orders#webhook"

  #Donation to Artist's Community
  get "/artists/donate/complete", to: "artists#donatesuccess", as:"donate_complete"
  post "/artists/:id/donate", to: "artists#donate", as:"artist_donate"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :artist
  has_many :orders
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Sets redirect to root path if user is not signed in and to avoid users seeing other users dashboards
    def dash
        if current_user.id != params[:id].to_i
            redirect_to home_path
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<h2>About <span class="tdc-name">Us</span></h2>

<p>Indigenous art isn't just about creativity, it is a direct link to their ancient culture and a way to pass this along to future generations. As indigenous people do not have a traditional "written history" prior to the interpreted and incomplete documentation by Europeans, this fundamental form of expression is crucial to the preservation of their past and the persistence of their culture into the future. Further, it is essential that indigenous people be provided with equal opportunities to provide for themselves and their communities via their work, both financially and culturally.<p>
<hr>
<br>
<%= image_tag src="940.jpg" %>
<hr>
<br>
<p>The upsides of providing a solution to this issue are numerous, such as:</p>

<ul>
    <li>Providing the appropriate level of ownership over their creations by indigenous artists</li>
    <li>Providing financial freedom and empowerment via a self-generated income stream</li>
    <li>Providing safeguards against the future exploitation of artists</li>
    <li>Providing channels for the production of authentic indigenous art direct from the source</li>
    <li>Providing assurance that any transactions with potential customers are ethical</li>
    <li>Providing a way for artists to feed this empowerment back into their communities to enable the improvement of infrastructure and a marked increase to quality of life</li>
</ul>
<br>
<h4>We are proud to provide <span class="tdc-name">The Dreaming Collective</span> as a sanctuary for the progress of these ideals.</h4>
<br>
<hr>
<br>
<p><%= link_to "Back", :back, class: "btn btn-info" %></p>

app/views/users/dash.html.erb
<%# If user is signed in, show dashboard via name link and redirect post-login %>
<% if user_signed_in? %>
    <h2>Your Dashboard</h2>
    <p>Welcome to your TDC Dashboard. We're proud to have you with us.</p>
    <%= link_to "Buy Art", all_items_path, class:"btn btn-primary" %>
    <%= link_to "Your Purchases", purchases_path, class:"btn btn-info" %>
    <% if !current_user.artist %>
        <%= link_to "Become An Artist", new_artist_path, class:"btn btn-dark" %>
    <% else %>
        <%= link_to "New Art Listing", new_item_path, class:"btn btn-success" %>
        <%= link_to "Your Sales", sales_path(current_user.artist.id), class:"btn btn-warning" %>
        <%= link_to "Edit Your Bio", edit_artist_path(current_user.artist.id), class:"btn btn-danger" %>
    <% end  %>
<% end %>
<hr>
<p><%= link_to "Back", :back, class: "btn btn-info" %></p>

app/views/users/index.html.erb
<h1>Welcome to  <span class="tdc-name">The Dreaming Collective</span></h1>

    <%= image_tag src="roo-art.jpg" %>

<%# # CAROUSEL TO BE EDITED %>

<%# <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div> %>