config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #Home Page
  root to: "users#index"
  get "/", to: "users#index", as: "home"

  #About Page
  get "/about", to: "users#about", as: "about"

  #Donate Page
  get "/donate", to: "users#donate", as: "donate"

  #User Dashboard
  get "/dashboard/:id", to: "users#dash", as: "dashboard"

  #Create new artwork item
  get "/items/new", to: "items#new", as: "new_item"
  post "/items", to: "items#create"

  #Show all art
  get "/items/all", to: "items#index", as: "all_items"

  #Show individual piece of art
  get "/items/:id", to: "items#show", as: "item"

  # Remove item listing
  delete "/items/:id", to: "items#destroy"

  #New Artist
  get "/artists/new", to: "artists#new", as: "new_artist"
  post "/artists", to: "artists#create"

  #Artist Profile
  get "/artists/:id/edit", to:"artists#edit", as: "edit_artist"
  put "/artists/:id", to: "artists#update"
  patch "/artists/:id", to: "artists#update"

  #Show Artists
  get "/artists/all", to: "artists#index", as: "all_artists"

  # Show individual Artist
  get "/artists/:id", to: "artists#show", as: "artist"
  
  # Sales/Purchase History 
  get "/orders/purchases", to: "orders#purchases", as: "purchases"
  get "/artists/:id/sales", to: "artists#sales", as: "sales"

  #New Order
  get "/orders/new", to: "orders#new", as: "new_order"

  #Order complete
  get "/orders/complete", to: "orders#complete"

  #Order Webhook
  post "/orders/webhook", to: "orders#webhook"

  #Donation to Artist's Community
  get "/artists/donate/complete", to: "artists#donatesuccess", as:"donate_complete"
  post "/artists/:id/donate", to: "artists#donate", as:"artist_donate"

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :artist
  has_one :order
  has_one_attached :item_image

  # Show all items, sorting by latest added
  def self.all_items
    items = Item.all.reverse_order
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    
    # Show all artwork
    def index
        @items = Item.all_items()
    end

    # Show selected artwork
    def show
        @item = Item.find(params[:id])
    end

    # New artwork
    def new
        @item = Item.new
    end

    # Create new artwork listing
    def create
        item = Item.new(item_params)
        item.artist_id = current_user.artist.id
        item.item_image.attach(params[:item][:item_image])
        if item.save
            flash[:notice] = "Deadly! Artwork added successfully."
            redirect_to item_path(item.id)
        else
            flash[:alert] = item.errors.full_messages[0]
            redirect_to new_item_path
        end
    end

    # Delete artwork listing (if user is owner)
    def destroy
        Item.destroy(params[:id])
        flash[:notice] = "Artwork was successfully removed from your Gallery."
        redirect_to dashboard_path
    end

    # Set artwork params
    private 
    def item_params
        params.require(:item).permit(:name,:category, :description, :price, :item_image)
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h2>Our <span class="tdc-name">Gallery</span></h2>
<br>
<%# Show each artwork listed on TDC %>
<%if @items %>
    <% @items.each do |item|%>
        <%= image_tag item.item_image, class: "img-thumbnail box", width: 200 if item.item_image.attached? %>
        <p><%= link_to item.name, item_path(item) %></p>
        <%# If user is the owner of that artwork, display remove button for deletion of piece %>
        <% if user_signed_in? && current_user.id == item.artist.user_id %>
            <p><%= link_to 'Remove', item, method: "delete", class:"btn btn-danger"%></p>
        <% end %>
    <%end%>
<%end%>
<hr>
<p><%= link_to "Back", :back, class: "btn btn-info" %></p>

app/views/items/new.html.erb
<h2>Add a new Artwork to your Gallery</h2>
<br>
<%# Form to add new art listing %>
<%= form_with model: @item do |form| %>
    <p>
        <%= label(:name, "Name") %>
        <%= form.text_field :name, required: true, minlength: 1 %>
    </p>
    <p>
        <%= label(:category, "Category") %>
        <%= form.text_field :category %>
    </p>
    <p>
        <%= label(:description, "Description") %>
        <%= form.text_area :description %>
    </p>
    <p>
        <%= form.label :price %>
        <%= form.number_field :price, min: 0, step: "0.01" %>
    </p>
    <p>
       <%= form.label :item_image, "Image"%>
       <%= form.file_field :item_image, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
    </p>
    
    <%= form.submit "Add Art", class: "btn btn-success" %>
<% end %>
<hr>
<p><%= link_to "Back", :back, class: "btn btn-info" %></p>

app/views/items/show.html.erb
<%# Show individual artwork listing %>
<h2><%= @item.name%></h2>
<br>
<%= image_tag @item.item_image, class: "img-thumbnail box", width: 400 if @item.item_image.attached? %>
<hr>
<h5><strong><%= @item.artist.user.first_name%> <%= @item.artist.user.last_name%></strong></h5>
<p><strong>Category:</strong> <%= @item.category%></p> 
<p><em><%= @item.description%></em></p> 
<% if @item.price %>
    <p><%= number_to_currency @item.price %></p>
    <% if user_signed_in? %>
        <%# if not sold show buy now button, otherwise hide button and show purchaser name %>
        <% if !@item.order %>
            <%= link_to "Buy Now", new_order_path(item_id: @item.id), class: "btn btn-success" %>
        <% else %>
            <p>Purchased by: <%= @item.order.user.first_name %> <%= @item.order.user.last_name %></p>
        <% end %>
    <% end %>
<% end  %>
<hr>
<p><%= link_to "Back", :back, class: "btn btn-info" %></p>